This is my (0x05. Python - Exceptions) Task.
